test_bridge: Resolve control reaching the end of a non-void function
mctp_binding_bridge_rx() was missing a return:

    tests/test_bridge.c: In function ‘mctp_binding_bridge_rx’:
    tests/test_bridge.c:60:1: error: no return statement in function returning non-void [-Werror=return-type]
       60 | }
          | ^
    cc1: all warnings being treated as errors

Signed-off-by: Andrew Jeffery <andrew@aj.id.au>
Change-Id: I2a52e872c4d4a0923e0fb14caf555c78dc57eabc