clang-tidy: wrap macro argument in parentheses
Fix ARRAY_SIZE macro to enclose argument in parentheses as required
by clang-tidy check bugprone-macro-parentheses, preventing build
failures under -warnings-as-errors.

Fixed below type errors
'''
../astlpc.c:173:43: error: macro argument should be enclosed in parentheses [bugprone-macro-parentheses,-warnings-as-errors]
  173 | #define ARRAY_SIZE(a) (sizeof(a) / sizeof(a[0]))
      |                                           ^
      |                                           ()
../core.c:30:43: error: macro argument should be enclosed in parentheses [bugprone-macro-parentheses,-warnings-as-errors]
   30 | #define ARRAY_SIZE(a) (sizeof(a) / sizeof(a[0]))
      |                                           ^
      |                                           ()
'''

Change-Id: Id843348f411d8b99fb83360b26e7c6da49136e4f
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>