test_serial: Resolve control reaching end of non-void function
mctp-binding_serial_pipe_tx() was missing a return:

    tests/test_serial.c: In function ‘mctp_binding_serial_pipe_tx’:
    tests/test_serial.c:34:1: error: control reaches end of non-void function [-Werror=return-type]
       34 | }
          | ^
    cc1: all warnings being treated as errors

Signed-off-by: Andrew Jeffery <andrew@aj.id.au>
Change-Id: Ia15a13fe4e283b76bfb4a856ea188a46ac5cf12c